import React,{useEffect,useState,useRef} from 'react';
import{createRoot}from'react-dom/client';import'./styles.css';
type Task={id:string;title:string;status:string;assignee:string;version:number};type Page={id:string;title:string;version:number};
const people={alice:'Admin · Pro',bob:'Member · Pro',viewer:'Viewer · Pro',sam:'Sales member · Pro',eve:'Rival admin · Free'};
function App(){const[user,setUser]=useState('alice'),[token,setToken]=useState(''),[tasks,setTasks]=useState<Task[]>([]),[pages,setPages]=useState<Page[]>([]),[ops,setOps]=useState<any>({usage:{},audit:[]}),[query,setQuery]=useState(''),[status,setStatus]=useState(''),[message,setMessage]=useState(''),[trace,setTrace]=useState<any[]>([]),[draft,setDraft]=useState<any>(),[busy,setBusy]=useState(false);const search=useRef<HTMLInputElement>(null);
 const request=async(path:string,options:RequestInit={})=>{const r=await fetch(path,{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,...options.headers}});const b=await r.json();if(!r.ok)throw new Error(b.message);return b};
 const login=async(u=user)=>{setBusy(true);try{const r=await fetch('/dev/token',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({subject:u})});const b=await r.json();setToken(b.access_token);setMessage(`Signed in as ${u}.`)}finally{setBusy(false)}};
 useEffect(()=>{login()},[user]);useEffect(()=>{if(!token)return;const t=setTimeout(()=>Promise.all([request(`/api/tasks?q=${encodeURIComponent(query)}&status=${status}`),request(`/api/pages?q=${encodeURIComponent(query)}`),request('/api/ops')]).then(([a,b,c])=>{setTasks(a.items);setPages(b.items);setOps(c)}).catch(e=>setMessage(e.message)),300);return()=>clearTimeout(t)},[token,query,status]);
 const prepare=async()=>{setBusy(true);try{const r=await request('/api/host/prepare',{method:'POST'});setDraft(r.draft);setTrace(r.trace);setMessage('Draft prepared. Review its exact text before approving.')}catch(e:any){setMessage(e.message)}finally{setBusy(false)}};
 const publish=async()=>{setBusy(true);try{const operation={title:draft.title,body:draft.body,taskIds:draft.taskIds,operationKey:draft.operationKey};const a=await request('/api/approve',{method:'POST',body:JSON.stringify(operation)});await request('/api/publish',{method:'POST',body:JSON.stringify({...operation,approvalId:a.approvalId})});setMessage('Page published.');setDraft(undefined);setTrace([]);const p=await request('/api/pages');setPages(p.items)}catch(e:any){setMessage(e.message)}finally{setBusy(false)}};
 return <div className="shell"><header><a className="brand" href="#top"><span>TS</span>Teamspace</a><nav aria-label="Course"><a href="#work">Work</a><a href="#trace">Host trace</a><a href="#lessons">Lessons</a></nav><label className="identity">Identity<select value={user} onChange={e=>setUser(e.target.value)}>{Object.entries(people).map(([k,v])=><option key={k} value={k}>{k} — {v}</option>)}</select></label></header>
 <main id="top"><section className="hero"><p className="eyebrow">MCP 103 · Operate the server</p><h1>Make every call<br/><em>survive reality.</em></h1><p>Fairness, budgets, jobs, safe ingestion and audit trails surround the same MCP surface. Change identities to see policy enforced at execution time.</p><div className="flow" aria-label="Architecture"><b>HOST</b><i>JSON-RPC</i><b>POLICY</b><i>scoped token</i><b>PRODUCT APIs</b></div></section>
 <section id="work" className="workspace"><div className="toolbar"><label htmlFor="search">Search this team</label><div className="search"><input ref={search} id="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Task or page title"/><button aria-label="Clear search" className={query?'':'hidden'} onClick={()=>{setQuery('');search.current?.focus()}}>×</button></div><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All</option><option value="todo">To do</option><option value="doing">Doing</option><option value="done">Done</option></select></label></div>
 <div className="columns"><article><div className="section-title"><h2>Team tasks</h2><small>{tasks.length} visible</small></div>{tasks.length?tasks.map(t=><div className="item" key={t.id}><span className={`state ${t.status}`}>{t.status}</span><div><strong>{t.title}</strong><small>{t.id} · {t.assignee} · v{t.version}</small></div></div>):<p className="empty">No tasks match. Clear filters or switch identity.</p>}</article><article><div className="section-title"><h2>Knowledge</h2><small>{pages.length} visible</small></div>{pages.length?pages.map(p=><div className="item page" key={p.id}><span>¶</span><div><strong>{p.title}</strong><small>{p.id} · revision {p.version}</small></div></div>):<p className="empty">No pages match this team and query.</p>}</article></div></section>
 <section id="trace" className="trace"><div><p className="eyebrow">Reference host</p><h2>Prepare a release note</h2><p>The fixture model selects tools deterministically. MCP retrieves data; the host owns approval.</p><button className="primary" disabled={busy} onClick={prepare}>{busy?'Working…':'Run the workflow'}</button></div><ol>{trace.length?trace.map((x,i)=><li key={i}><b>{x.layer}</b><span>{x.event}</span><code>{JSON.stringify(x.data).slice(0,240)}</code></li>):<li className="empty">Run the workflow to reveal the model, host, and MCP boundaries.</li>}</ol></section>
 {draft&&<div className="modal-back"><div role="dialog" aria-modal="true" aria-labelledby="approval-title" className="modal"><p className="eyebrow">Consequential action</p><h2 id="approval-title">Publish this exact page?</h2><label>Title<input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>Markdown<textarea rows={10} value={draft.body} onChange={e=>setDraft({...draft,body:e.target.value})}/></label><div className="actions"><button onClick={()=>setDraft(undefined)}>Cancel</button><button className="primary" disabled={busy} onClick={publish}>Approve and publish</button></div></div></div>}
 <section className="trace"><div><p className="eyebrow">Operations</p><h2>Budget and audit</h2><p>Spent {ops.usage?.spent??0} · reserved {ops.usage?.reserved??0} · allowance {ops.usage?.allowance??0}</p></div><ol>{ops.audit?.length?ops.audit.map((x:any,i:number)=><li key={i}><b>{x.outcome}</b><span>{x.operation}</span><code>{x.trace_id}</code></li>):<li className="empty">Run a workflow to create redacted audit events.</li>}</ol></section>
 <section id="lessons" className="lessons"><p className="eyebrow">Guided checkpoints</p><h2>Harden it in ten passes</h2>{[['trust-boundaries','Trust boundaries'],['fairness-and-limits','Fairness and limits'],['budgets-and-entitlements','Budgets and entitlements'],['retries-and-idempotency','Retries and idempotency'],['fallbacks-and-circuits','Fallbacks and circuits'],['safe-url-import','Safe URL import'],['durable-tasks','Durable tasks'],['composition','Composition'],['observability','Observability'],['deployment','Deployment']].map(([slug,x],i)=><a href={`/course/${String(i+1).padStart(2,'0')}-${slug}.md`} key={x}><small>{String(i+1).padStart(2,'0')}</small>{x}</a>)}</section><div role="status" aria-live="polite" className="toast">{message}</div></main></div>}
createRoot(document.getElementById('root')!).render(<App/>);
